Repository TuranicTeam/Altay, pull requests merged in 2020-06, with the labels that each got.

#258 Fixed mountEntity function
  src/pocketmine/entity/Entity.php
Labels: Category: Gameplay, PR: Bug Fix

#261 Implement Emotes
  src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter.php
Labels: Category: Gameplay, PR: Feature, Status: WIP

#263 Fixed EntityLink in sendSpawnPacket function
  src/pocketmine/entity/Entity.php
Labels: Category: Core, PR: Bug Fix
